name: 'telelink_dbt'
version: '1.0'
config-version: 2

profile: 'telelink_snowflake'

source-paths: ['models']
macro-paths: ['macros']

models:
  telelink_dbt:
    staging:
      +schema: staging
      +materialized: incremental
    silver:
      hubs:
        +schema: silver
        +materialized: incremental
      links:
        +schema: silver
        +materialized: incremental
      satellites:
        +schema: silver
        +materialized: incremental
    gold:
      +schema: gold
      +materialized: table
      sales:
        +schema: gold_sales
        +materialized: table
      hr:
        +schema: gold_hr
        +materialized: table
      inventory:
        +schema: gold_inventory
        +materialized: table
    sources:
      +schema: bronze
      +materialized: view
