version: 2

description: "Gold layer models for HR domain"

models:
  - name: dim_employee
    description: "Employee dimension table"
    columns:
      - name: employee_key
        description: "Primary key for the employee dimension"
        tests:
          - unique
          - not_null
      - name: employee_id
        description: "Business key from source system"
        tests:
          - not_null
      - name: first_name
        description: "Employee first name"
      - name: last_name
        description: "Employee last name"
      - name: full_name
        description: "Employee full name (first + last)"
      - name: date_of_birth
        description: "Employee date of birth"
      - name: gender
        description: "Employee gender"
      - name: hire_date
        description: "Date the employee was hired"
      - name: email
        description: "Employee email address"
      - name: phone
        description: "Employee phone number"
      - name: address
        description: "Employee address"
      - name: employment_status
        description: "Current employment status (Active, Terminated, On Leave, etc.)"
      - name: effective_from
        description: "Date from which this employee record is effective"
      - name: effective_to
        description: "Date until which this employee record is effective"
      - name: is_current
        description: "Flag indicating if this is the current record for the employee"

  - name: dim_department
    description: "Department dimension table"
    columns:
      - name: department_key
        description: "Primary key for the department dimension"
        tests:
          - unique
          - not_null
      - name: department_id
        description: "Business key from source system"
        tests:
          - not_null
      - name: department_name
        description: "Department name"
      - name: location
        description: "Department location"
      - name: manager_key
        description: "Foreign key to employee dimension (manager)"
      - name: effective_from
        description: "Date from which this department record is effective"
      - name: effective_to
        description: "Date until which this department record is effective"
      - name: is_current
        description: "Flag indicating if this is the current record for the department"

  - name: dim_job_position
    description: "Job position dimension table"
    columns:
      - name: job_key
        description: "Primary key for the job position dimension"
        tests:
          - unique
          - not_null
      - name: job_id
        description: "Business key from source system"
        tests:
          - not_null
      - name: job_title
        description: "Job title"
      - name: job_level
        description: "Job level"
      - name: job_family
        description: "Job family"
      - name: description
        description: "Job description"
      - name: effective_from
        description: "Date from which this job position record is effective"
      - name: effective_to
        description: "Date until which this job position record is effective"
      - name: is_current
        description: "Flag indicating if this is the current record for the job position"

  - name: dim_benefit_plan
    description: "Benefit plan dimension table"
    columns:
      - name: benefit_plan_key
        description: "Primary key for the benefit plan dimension"
        tests:
          - unique
          - not_null
      - name: benefit_plan_id
        description: "Business key from source system"
        tests:
          - not_null
      - name: plan_name
        description: "Benefit plan name"
      - name: plan_type
        description: "Type of benefit plan"
      - name: provider
        description: "Benefit plan provider"
      - name: effective_from
        description: "Date from which this benefit plan record is effective"
      - name: effective_to
        description: "Date until which this benefit plan record is effective"
      - name: is_current
        description: "Flag indicating if this is the current record for the benefit plan"

  - name: fact_employment
    description: "Employment fact table"
    columns:
      - name: employment_key
        description: "Primary key for the employment fact"
        tests:
          - unique
          - not_null
      - name: employee_key
        description: "Foreign key to employee dimension"
        tests:
          - relationships:
              to: ref('dim_employee')
              field: employee_key
      - name: job_key
        description: "Foreign key to job position dimension"
        tests:
          - relationships:
              to: ref('dim_job_position')
              field: job_key
      - name: department_key
        description: "Foreign key to department dimension"
        tests:
          - relationships:
              to: ref('dim_department')
              field: department_key
      - name: start_date_key
        description: "Foreign key to date dimension (start date)"
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: end_date_key
        description: "Foreign key to date dimension (end date)"
      - name: manager_key
        description: "Foreign key to employee dimension (manager)"
      - name: is_current
        description: "Flag indicating if this is the current employment record"

  - name: fact_compensation
    description: "Compensation fact table"
    columns:
      - name: compensation_key
        description: "Primary key for the compensation fact"
        tests:
          - unique
          - not_null
      - name: compensation_id
        description: "Business key from source system"
      - name: employee_key
        description: "Foreign key to employee dimension"
        tests:
          - relationships:
              to: ref('dim_employee')
              field: employee_key
      - name: effective_date_key
        description: "Foreign key to date dimension (effective date)"
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: base_salary
        description: "Base salary amount"
      - name: currency
        description: "Currency of the compensation"
      - name: bonus_eligible
        description: "Flag indicating if the employee is eligible for bonus"
      - name: is_current
        description: "Flag indicating if this is the current compensation record"

  - name: fact_benefit_enrollment
    description: "Benefit enrollment fact table"
    columns:
      - name: enrollment_key
        description: "Primary key for the benefit enrollment fact"
        tests:
          - unique
          - not_null
      - name: enrollment_id
        description: "Business key from source system"
      - name: employee_key
        description: "Foreign key to employee dimension"
        tests:
          - relationships:
              to: ref('dim_employee')
              field: employee_key
      - name: benefit_plan_key
        description: "Foreign key to benefit plan dimension"
        tests:
          - relationships:
              to: ref('dim_benefit_plan')
              field: benefit_plan_key
      - name: enrollment_date_key
        description: "Foreign key to date dimension (enrollment date)"
        tests:
          - relationships:
              to: ref('dim_date')
              field: date_key
      - name: coverage_level
        description: "Level of coverage"
      - name: is_current
        description: "Flag indicating if this is the current enrollment record"
